import "./globals.css";
import AppProvider from "@/components/context/AppProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
