/*Configuración proyecto*/
DROP TABLE IF EXISTS material_fase CASCADE;
DROP TABLE IF EXISTS fase_ensamble_pieza_conf CASCADE;
DROP TABLE IF EXISTS proceso_ensamble_pieza_conf CASCADE;
DROP TABLE IF EXISTS material_pieza_conf CASCADE;
DROP TABLE IF EXISTS pieza_caracteristica CASCADE;
DROP TABLE IF EXISTS caracteristica_pieza_conf CASCADE;
DROP TABLE IF EXISTS fase_prueba CASCADE;
DROP TABLE IF EXISTS modelo_prueba CASCADE;
DROP TABLE IF EXISTS prueba_conf CASCADE;
DROP TABLE IF EXISTS avion_componente CASCADE;
DROP TABLE IF EXISTS composicion CASCADE;
DROP TABLE IF EXISTS modelo_pieza_conf CASCADE;
DROP TABLE IF EXISTS fase_ensamble_avion_conf CASCADE;
DROP TABLE IF EXISTS proceso_ensamble_avion_conf CASCADE;
DROP TABLE IF EXISTS modelo_avion_caracteristica CASCADE;
DROP TABLE IF EXISTS modelo_avion_conf CASCADE;
DROP TABLE IF EXISTS caracteristica_anv_conf CASCADE;
DROP TABLE IF EXISTS tipo_avion CASCADE;

/*Esperando las correcciones de anak*/


DROP TABLE IF EXISTS asistencia CASCADE;
DROP TABLE IF EXISTS emp_cargo_horario CASCADE;
DROP TABLE IF EXISTS emp_cargo_horario  CASCADE;
DROP TABLE IF EXISTS horario CASCADE;
DROP TABLE IF EXISTS empleado_cargo CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;

/*Parte IZQUIERDA*/
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS privilegio_rol CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS privilegio CASCADE;
DROP TABLE IF EXISTS empleado_titulo CASCADE;
DROP TABLE IF EXISTS titulo CASCADE;
DROP TABLE IF EXISTS per_ben CASCADE;
DROP TABLE IF EXISTS beneficiario CASCADE;
DROP TABLE IF EXISTS experiencia CASCADE;
DROP TABLE IF EXISTS empleado CASCADE;
DROP TABLE IF EXISTS cliente_juridico CASCADE;
DROP TABLE IF EXISTS cliente_natural CASCADE;
DROP TABLE IF EXISTS pago_nomina CASCADE;
DROP TABLE IF EXISTS correo_electronico CASCADE;
DROP TABLE IF EXISTS red_social CASCADE;
DROP TABLE IF EXISTS TELEFONO CASCADE;

/*Esperando las correcciones de anak*/
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS proveedor_mp_stock CASCADE;
DROP TABLE IF EXISTS materia_prima CASCADE;



/*Lugar geográfico*/
DROP TABLE IF EXISTS  lugar CASCADE;

/*Pago*/

DROP TABLE IF EXISTS moneda CASCADE;
DROP TABLE IF EXISTS metodo_pago CASCADE;
